### ISSUE TITLE
feat: 考虑增加一些调度过滤功能

### ISSUE THREAD

**Issue by googs1025** [Kubernetes-Learning-Playground/multi-clusters#27]
```yaml
   placement:
     clusters:
       - name: tencent1
       - name: tencent2
       - name: tencent4
```

目前只有简单字段，考虑增加 clusterSelector字段
